# Investigating Global Temperatures and El Nino

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

## Reading the Global Temperature and ONI data 

I downloaded global datasets for ONI and Global Temperatures 

Specifically these are

- ONI: [NOAA PSL Ocean Nino Index](https://climatedataguide.ucar.edu/climate-data/nino-sst-indices-nino-12-3-34-4-oni-and-tni). This data contain computed monthly ONI anomalies
- [Berkeley Global Temperature Anomaly (1850 to Recent)](https://berkeleyearth.org/data/)

The code below reads these data into a pandas dataframes and reformats them to be a simple timeseries.

In [1]:
ONI_data = '../Data/oni.data'
oni_data = pd.read_csv(ONI_data, sep=r'\s+', skiprows=1, header = None, skipfooter=8, index_col=0) 
oni_data.head()

NameError: name 'pd' is not defined

In [65]:
df_oni= oni_data.stack() # converts the dataframe into a series with a multi-index of Year and Month 
df_oni= pd.DataFrame(df_oni) # converts the series back into a dataframe
df_oni.index.rename(['Year','Month'],inplace=True) # renames the multi-index levels to Year and Month
df_oni=df_oni.reset_index() # resets the index so that Year and Month become columns instead of index levels
df_oni.columns=['Year','Month','ONI'] # renames the columns to Year, Month, and ONI
df_oni['Date'] = pd.to_datetime(df_oni['Year'].astype(str) + '-' + df_oni['Month'].astype(str), format='%Y-%m') # converts year and month into a datetime object   
df_oni = df_oni.set_index('Date').drop(columns=['Year','Month'])# sets the date as the index and drops the Year and Month columns
df_oni.head()

             ONI
Date
1950-01-01 -1.53
1950-02-01 -1.34
1950-03-01 -1.16
1950-04-01 -1.18
1950-05-01 -1.07

In [66]:
berkeley_temperature_data = '../Data/Global_TAVG_monthly.txt'

df_temp = pd.read_csv(berkeley_temperature_data, sep=r'\s+', skiprows=95, header=None, 
                      names=['Year', 'Month', 'T_month_anomaly', 'T_month_uncertainty'], 
                      usecols=[0, 1, 2, 3])
df_temp=df_temp.reset_index(drop=True) # resets the index to be a simple range index
df_temp['Date'] = pd.to_datetime(df_temp['Year'].astype(str) + '-' + df_temp['Month'].astype(str), format='%Y-%m')
df_temp = df_temp.set_index('Date').drop(columns=['Year','Month'])# sets the date as the index and drops the Year and Month columns
df_temp.head()

            T_month_anomaly  T_month_uncertainty
Date
1850-01-01           -0.380                0.394
1850-02-01           -0.186                0.407
1850-03-01           -0.220                0.463
1850-04-01           -0.738                0.631
1850-05-01           -0.276                0.634

## Create a common dataframe for our analysis that covers the same time

## Perform Exploratory Analysis

## Investigate Trends of Global Temperature Data

## Investigate how El Nino Affects Global Temperatures

- Remember that for El Nino ONI >0.5 and for La Nina ONI < -0.5

- You can think about 
    - temperature distributions
    - temperature trends for El Nino and La Nina
    - a linear model that includes ONI
    - significance tests